# Generated by Django 4.0.5 on 2022-06-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.IntegerField(default=1),
        ),
    ]
