# Generated by Django 4.0.5 on 2022-06-29 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortal', '0002_alter_author_user_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorNew',
        ),
    ]
