# Generated by Django 4.0.5 on 2022-06-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_rename_authornew_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user1',
        ),
    ]
