# Generated by Django 4.0.5 on 2022-06-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0005_rename_user_author_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user1',
            new_name='user',
        ),
    ]
